### ISSUE TITLE
desktop: insufficient margin on resources link

### ISSUE THREAD

**Issue by diachedelic** [Stjep1/DECO1016#4]
https://stjep1.github.io/DECO1016/firstTute.html

![image](https://user-images.githubusercontent.com/310464/48179773-d7246c00-e374-11e8-8e11-18d7b88be839.png)

**Comment by Stjep1** [comment]
I fixed the positioning. It looks good on my laptop now. But. When I change the screen size, it goes all over the place.

**Comment by diachedelic** [comment]
Have you pushed your changes to github?  I can't see a change

**Comment by diachedelic** [comment]
You are really making things hard for yourself by using `position: absolute` everywhere, it's not gonna be responsive if you do that.

```css
.resBox {
    width: 300px;
    height: 50px;
    padding: 0px;
    background-color: #111;
    position: absolute;
    left: 770px;
    bottom: 500px;
}
```

Also, seeing as it's aligned to the right side of the page, why did you use `left: 770px`?  You basically can't assume that the page is going to have specific dimensions.  Try resizing your browser as you make changes so you can make sure elements stay in a sane place
