### ISSUE TITLE
desktop: items overflow homepage

### ISSUE THREAD

**Issue by diachedelic** [Stjep1/DECO1016#5]
Is it supposed to scroll horizontally?  It looks like a mistake that the whole title is not visible immediately

https://stjep1.github.io/DECO1016/

![image](https://user-images.githubusercontent.com/310464/48179811-0b982800-e375-11e8-9878-472c258ebc1f.png)

**Comment by Stjep1** [comment]
Nope its supposed to be in the centre of the head, and it is in the centre on a desktop, but on a laptop it skews to one side

**Comment by diachedelic** [comment]
Your code for the `.titleBox` is overly complex.  You should be able to remove the `.titleText` element, and apply *only* these styles to `.titleBox`:

```css
.titleBox {
    padding: 16px;
    /* same as #666, but slightly translucent */
    background-color: rgba(102, 102, 102, 0.8);
    color: white;
    font: bold 50px "Lato",sans-serif;
    letter-spacing: 8px;
    text-transform: uppercase;
    white-space: nowrap; /* stop the text wrapping around */
    /* horizontal centring */
    position: absolute;
    top: 50px;
    left: 50%;
    transform: translateX(-50%);
}
```
